CREATE TABLE IF NOT EXISTS TrackingSystem.ACTIVITY 
(
CREATEDATE timestamp NOT NULL,
SRNUMBER char(64) NOT NULL,
`UPDATE` text ,
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN',
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN',
CREATED_AT timestamp NOT NULL DEFAULT NOW(),
UPDATED_AT timestamp  NOT NULL DEFAULT NOW(),
PRIMARY KEY (CREATEDATE),
FOREIGN KEY (SRNUMBER) REFERENCES SERVICEREQUEST (SRNUMBER)
);