CREATE TABLE TrackingSystem.ACCOUNT 
(ACCOUNTID integer AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME char(100) ,
LAST_NAME char(100) ,
ADDRESS1 varchar(200),
ADDRESS2 varchar(200) ,
CITY varchar(100) ,
STATE char(50) ,
ZIPCODE char(30),
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN', 
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN', 
CREATED_AT timestamp NOT NULL DEFAULT NOW(),
UPDATED_AT timestamp  NOT NULL DEFAULT NOW(),
INDEX name (FIRST_NAME ,LAST_NAME)
);
