CREATE TABLE TrackingSystem.ACCOUNT 
(ACCOUNTID integer AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME char(100) ,
LAST_NAME char(100) ,
ADDRESS1 varchar(200),
ADDRESS2 varchar(200) ,
CITY varchar(100) ,
STATE char(50) ,
ZIPCODE char(30),
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN', 
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN', 
CREATED_AT timestamp NOT NULL DEFAULT NOW(),
UPDATED_AT timestamp  NOT NULL DEFAULT NOW(),
INDEX name (FIRST_NAME ,LAST_NAME)
);


CREATE TABLE IF NOT EXISTS TrackingSystem.CONTACT 
(CONTACTID integer AUTO_INCREMENT,
ACCOUNTID integer ,
LASTNAME CHAR(50) ,
FIRSTNAME CHAR(50),
PHONE char(40) ,
EMAIL CHAR(100) ,
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN',
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN',
CREATED_AT timestamp NOT NULL DEFAULT NOW(),
UPDATED_AT timestamp  NOT NULL DEFAULT NOW(),
PRIMARY KEY (CONTACTID ),
FOREIGN KEY (ACCOUNTID)
REFERENCES ACCOUNT (ACCOUNTID));




CREATE TABLE IF NOT EXISTS TrackingSystem.SERVICEREQUEST 
(SRNUMBER char(64) ,
TITLE VARCHAR(512) ,
ACCOUNTID integer NOT NULL,
CONTACTID integer NOT NULL,
STATUS char(20) ,
OPENDATE timestamp DEFAULT CURRENT_TIMESTAMP,
CLOSEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
DESCRIPTION varchar(512),
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN', 
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN', 
CREATED_AT timestamp NOT NULL DEFAULT NOW(),
UPDATED_AT timestamp  NOT NULL DEFAULT NOW(),
PRIMARY KEY (SRNUMBER),
INDEX date (OPENDATE ,CLOSEDATE));

CREATE TABLE IF NOT EXISTS TrackingSystem.ACTIVITY 
(ACTID integer AUTO_INCREMENT PRIMARY KEY,
CREATEDATE timestamp NOT NULL,
SRNUMBER char(64) NOT NULL,
`UPDATE` text ,
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN',
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN',
CREATED_AT timestamp NOT NULL DEFAULT NOW(),
UPDATED_AT timestamp  NOT NULL DEFAULT NOW(),
FOREIGN KEY (SRNUMBER) REFERENCES SERVICEREQUEST (SRNUMBER)
);



