CREATE TABLE TrackingSystem.ACCOUNT 
(ACCOUNTID integer AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME varchar(100) ,
LAST_NAME varchar(100) ,
ADDRESS1 varchar(200),
ADDRESS2 varchar(200) ,
CITY varchar(100) ,
STATE varchar(50) ,
ZIPCODE varchar(30),
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN', 
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN', 
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
INDEX name (FIRST_NAME ,LAST_NAME)
);


CREATE TABLE IF NOT EXISTS TrackingSystem.CONTACT 
(CONTACTID integer AUTO_INCREMENT,
ACCOUNTID integer ,
LASTNAME varchar(50) ,
FIRSTNAME varchar(50),
PHONE varchar(40) ,
EMAIL varchar(100) ,
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN',
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN',
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (CONTACTID ),
FOREIGN KEY (ACCOUNTID)
REFERENCES TrackingSystem.ACCOUNT (ACCOUNTID));




CREATE TABLE IF NOT EXISTS TrackingSystem.SERVICEREQUEST 
(SRNUMBER varchar(64) ,
TITLE VARCHAR(512) ,
ACCOUNTID integer NOT NULL,
CONTACTID integer NOT NULL,
STATUS varchar(20) ,
OPENDATE timestamp DEFAULT CURRENT_TIMESTAMP,
CLOSEDATE timestamp DEFAULT CURRENT_TIMESTAMP,
DESCRIPTION varchar(512),
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN', 
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN', 
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (SRNUMBER),
INDEX date (OPENDATE ,CLOSEDATE));

CREATE TABLE IF NOT EXISTS TrackingSystem.ACTIVITY 
(ACTID integer AUTO_INCREMENT PRIMARY KEY,
CREATEDATE timestamp NOT NULL,
SRNUMBER varchar(64) NOT NULL,
`UPDATE` text ,
CREATED_BY varchar(200) DEFAULT 'SYS_ADMIN',
UPDATED_BY varchar (200) DEFAULT 'SYS_ADMIN',
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (SRNUMBER) REFERENCES TrackingSystem.SERVICEREQUEST (SRNUMBER)
);


